### ISSUE TITLE
Error importing contextily 

### ISSUE THREAD

**Issue by mygethub-99** [darribas/contextily#104]
Running PY 3.7.0.final.0 on anaconda, conda version 4.6.8, conda-build version 3.15.1
Installed contextily from conda-forge. Install completed without errors.

import contextily
Traceback (most recent call last):

  File "<ipython-input-1-41c91ce4237a>", line 1, in <module>
    import contextily

  File "C:\Users\ow4253\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\contextily\__init__.py", line 7, in <module>
    from .place import Place, plot_map

  File "C:\Users\ow4253\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\contextily\place.py", line 6, in <module>
    from .tile import howmany, bounds2raster, bounds2img, _sm2ll, _calculate_zoom

  File "C:\Users\ow4253\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\contextily\tile.py", line 20, in <module>
    from rasterio.io import MemoryFile

ImportError: No module named 'rasterio.io'

**Comment by jorisvandenbossche** [comment]
This is a problem with the installation of `rasterio`, not directly of `contextily`. 

There are currently some problems with the latest packages of rasterio on windows (see eg https://github.com/conda-forge/rasterio-feedstock/issues/149). In one of those discussions, I saw the suggestion to install an older version of rasterio (`conda install rasterio=1.0.13 -c conda-forge`)

**Comment by mygethub-99** [comment]
Thank you, I will give this a try.
